# Generated by Django 5.0.6 on 2024-09-25 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(help_text="Masukkan perintah seperti '/start', 'hello', dll.", max_length=255)),
                ('response', models.TextField(help_text='Masukkan respons yang akan dikirim saat perintah diterima.')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='bots.bot')),
            ],
            options={
                'verbose_name': 'Bot Command',
                'verbose_name_plural': 'Bot Commands',
                'unique_together': {('bot', 'command')},
            },
        ),
    ]
